# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-05 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twt_coop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthTokenTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('oauth_token_secret', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
